# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workout.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('human_readable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_date', models.DateField(verbose_name='Performed')),
                ('registered_date', models.DateField(verbose_name='Registered')),
                ('comment', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=models.SET(workout.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary', to='workout.ActivityType')),
                ('secondary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary', to='workout.ActivityType')),
            ],
        ),
    ]
